theme: forest-bg.png
title: Manaflux
description: An assistant that can choose your runes, summoner spells, and item sets for League of Legends.
download:
  windows: https://github.com/Ryzzzen/manaflux/releases/download/v2.0.3/manaflux-setup-2.0.3.exe
repository: ryzzzen/manaflux
baseurl: /manaflux
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
