theme: forest-bg.png
title: Manaflux
description: An assistant that can choose your runes, summoner spells, and item sets for League of Legends.
repository: ryzzzen/manaflux
baseurl: /manaflux
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
repository: Ryzzzen/Manaflux
